/*
<<copyright 2013 Pablo Sánchez Robles>>
This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
     any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
*/
/*
 * MiVentanaInterna.java
 *
 * Created on 16-abr-2013, 20:25:47
 */

package minipaint;

import javax.swing.JScrollPane;

/**
 * Clase que muestra un objeto de tipo lienzo en una ventana.
 * @author Pablo Sánchez Robles
 */
/*
 *  Ésta clase sólo es contenedora de un objeto de la clase Lienzo
 */
public class MiVentanaInterna extends javax.swing.JInternalFrame {

    /** Creates new form MiVentanaInterna */
    public MiVentanaInterna() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo1 = new minipaint.Lienzo();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(null);
        jScrollPane1.setMinimumSize(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 500));
        jScrollPane1.setSize(new java.awt.Dimension(500, 500));

        lienzo1.setMaximumSize(null);
        lienzo1.setMinimumSize(null);
        lienzo1.setPreferredSize(new java.awt.Dimension(500, 500));
        jScrollPane1.setViewportView(lienzo1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public minipaint.Lienzo getLienzo(){return lienzo1;}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public minipaint.Lienzo lienzo1;
    // End of variables declaration//GEN-END:variables

}
